<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions"/>
    <PackageReference Include="xunit"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\IncomeTax\IncomeTax.csproj" />
  </ItemGroup>
</Project>